org.wildfly.datasources.mssqlserver.connection-url=jdbc:sqlserver://[SERVER_DB]:[PORT_DB];databaseName=[DATABASE_NAME];encrypt=true;trustServerCertificate=true

org.wildfly.datasources.mssqlserver.user-name=[USER_BD]
org.wildfly.datasources.mssqlserver.password=[PASSWORD_BD]

org.wildfly.datasources.mssqlserver.jndi-name=java:jboss/datasources/InventarioDS

org.wildfly.datasources.mssqlserver.min-pool-size=2
org.wildfly.datasources.mssqlserver.max-pool-size=10

org.wildfly.datasources.mssqlserver.jta=true