org.wildfly.datasources.mssqlserver.connection-url=jdbc:sqlserver://localhost:1433;databaseName=InventarioDB;encrypt=true;trustServerCertificate=true

org.wildfly.datasources.mssqlserver.user-name=inventario_app
org.wildfly.datasources.mssqlserver.password=Inventario2026!

org.wildfly.datasources.mssqlserver.jndi-name=java:jboss/datasources/InventarioDS

org.wildfly.datasources.mssqlserver.min-pool-size=2
org.wildfly.datasources.mssqlserver.max-pool-size=10

org.wildfly.datasources.mssqlserver.jta=true